version: "3.8"
services: 
  fastapi:
    container_name: iqoption_trader
    build: .
    command: uvicorn main:server --workers ${WEB_CONCURRENCY} --host 0.0.0.0 --port 8000
    ports: 
      - "${APP_PORT}:8000"
    restart: always
